language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
install: npm install
script:
- export
- REACT_APP_BACKEND="" npm test
- test $TRAVIS_BRANCH = "master" && npm run build
deploy:
  provider: s3
  access_key_id:
    secure: bRA/3Q/ZXjLL0xJehcjMW9KkQG7z0YWgfXmGJUBoDt8L6C2uNkaXQZqGBMC7hDh7TGcqI3PupzOMJDgMiiPYOOJAW/9C5UEd6CEPsAyb01zUb6K9DjeVk7Z5KoeAS5FR25ywrmYyHykwoz6ysOLD+W9xBZJx/V4zHlJK3neXsZjzChoFhElwLbUiJpI6F4u/arNuxhkEUJxhAYkCZFhjDAm/izzvaAV6peT0EO2+GH4FXiembxd30pHFjtUGSXctJs3w+RF7xMbn3Y9+vUoiE9/5oec305HXccP29slpSWs9BrYlategyNq8muWy/wIrNK86HiXS5UB1CrR38KIR1BTatcVXreDI4CkTNSx7JQ6T0SWcufa4n/GhvIeH6LJwvlcS+wGFy2LhJAqHhHbX/XIzTAhirJnDjLuqp2ASB6am7k+1SwXciMeKDDn1Hzs61FSTnsJbeDE/GDnHhrYEefDKluTV54uWdPtKJcIlL+uIh5n1kYR2zYIPsyBGCtKc4ogpZG9JrWu6KzaN1nu2Nlw6uxnMTelWCC2jebtKZI1ZqBFGwom63i7n9kgBW8JomGZZqCGCZJ8LAxRxCg9r5XHYV/shmOIH1QMxaS6HBFXOp3bVKLbLFel8AvDc7I4prETUoZdjht6KKgFysWDDb5RtpAsuneGMJGkzhJIIVOI=
  secret_access_key:
    secure: QCMlWaLufQXcy7BG/1oq/PVgIp5RXvZb12koO+2ZkoCOci2QNgpFskIy6NHs/XbDclJbhnDoyK2bf0EW022OVm7UwAGAzIdIhnv000+M4TXl4rUf5zV5g/0c/yhJjzcHkz5Zys9pL4N/NmnJ1vR+l+YcFeD5mpg/1kMUkxYYcqKEvqeyiOy8EGfaE5HuDznBwMU93dV+sRzDm0wBg3TxDoQQUT61FIhQg6NtbulSu2F9PQ3feaswiq9FSrsSCHm/f6vjiAsSHITZU+DUmUzzTazUoJc5nL/aS78QkX/E0m8GcQ6Fz0D++dWciZW60Hr+l+f+0OBE9nKptiKyeiMLyMpBhjJJQYBi3jIM7IQdF0gi+5UVzVYBbiAMUl7J3OdRayiSymmcQNkHBCSi+NRlOgDsc1X485ASMBFEYDD+NZu6wG8oscj1Vl+7Ku+mMVpjZTRppQzeNxqTZYG3HCViv/szrKfIPJlLQyfQelVnOnGDeMxH7xQxh6bgG43mftKESn6t2snxsnYUJzA3Abhayldsmiy2hmszp2AjoZhCJ9VszyhZpuCOgCmCLfK7p431smF/doxpUUy3/sEzvQb8zZ8z4hHqirucsxJ7rjSPlhOTiWoAJs/neS6ysoGQyIeVAXWYAgosYclxUNtu2h0Rn2fZ2g7ZxXBlkCSn18qWktc=
  bucket: glam.esciencecenter.nl
  skip_cleanup: true
  region: eu-central-1
  local_dir: build
  on:
    branch: master
env:
  matrix:
  - COMMIT=${TRAVIS_COMMIT::8} REACT_APP_BACKEND=/api
